Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

AllCops:
  Exclude:
    - 'db/schema.rb'
