env:
  global:
    - DB_USER=postgres
    - DB_PSWD=postgres
    - DB_HOST=localhost
    - CC_TEST_REPORTER_ID=043fa33f7b4ca0260700d21c051483f7f8b98501f7f6ba09a63673e8b03fd51e
language: ruby
rvm:
  - 2.4.2
before_script:
  - psql -c 'create database app_test;' -U $DB_USER
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
cache:
  - bundler
services:
  - postgresql
test:
  adapter: postgresql
  database: app_test
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
